# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


plugin 'cocoapods-art', :sources => [
  'cocoa-pro-fphi'
]

source 'https://cdn.cocoapods.org/'

fphi_pods = "remote"

def remote_pods
  pod 'FPHISDKMainComponent', '~> 2.5.0'
  pod 'FPHISDKSelphIDComponent', '~> 2.5.0'
  pod 'FPHISDKSelphiComponent', '~> 2.5.0'
  pod 'FPHISDKStatusComponent', '~> 2.5.0'
  pod 'FPHISDKTokenizeComponent', '~> 2.5.0'
  pod 'FPHISDKTrackingComponent', '~> 2.5.0'
  pod 'FPHISDKVideoRecordingComponent', '~> 2.5.0'
end

target 'demosdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  if fphi_pods == "remote"
    remote_pods
  end

end


## zipzap fix
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'zipzap'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
