# Uncomment the next line to define a global platform for your project
plugin 'cocoapods-art', :sources => [
'cocoa-pro-fphi'
]

source 'https://cdn.cocoapods.org/'

target 'demosdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'FPHISDKSelphIDComponent', '~> 2.8.2'
#  pod 'FPHISDKSelphIDLightComponent', '~> 2.8.2'
#  pod 'FPHISDKSelphIDFullComponent', '~> 2.8.2'
  pod 'FPHISDKSelphIDMBSDRComponent', '~> 2.8.2'
#  pod 'FPHISDKSelphIDMLRGLComponent', '~> 2.8.2'
#  pod 'FPHISDKSelphIDRGLComponent', '~> 2.8.2'
  pod 'FPHISDKCaptureComponent', '~> 2.8.1'
  pod 'FPHISDKMainComponent', '~> 2.8.1'
  pod 'FPHISDKNFCComponent', '~> 2.16.1'
  pod 'FPHISDKSelphiComponent', '~> 2.8.2'
  pod 'FPHISDKStatusComponent', '~> 2.8.1'
  pod 'FPHISDKTokenizeComponent', '~> 2.8.1'
  pod 'FPHISDKTrackingComponent', '~> 2.8.1'
  pod 'FPHISDKVideoRecordingComponent', '~> 2.8.1'
  pod 'FPHISDKVideoIDComponent', '~> 2.8.1'
  pod 'FPHISDKVoiceIDComponent', '~> 2.8.1'
  pod 'FPHISDKPhingersTFComponent', '~> 2.8.1'

  pod 'FPHISDKVideoCallComponent', '~> 2.8.3'
end

target 'videocallExtension' do
   use_frameworks!
  pod 'FPHISDKVideoCallComponent', '~> 2.8.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'zipzap'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
