# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


plugin 'cocoapods-art', :sources => [
  'cocoa-pro-fphi'
]

source 'https://cdn.cocoapods.org/'

target 'demosdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # TODO: Check why do we need this
  pod 'IQKeyboardManagerSwift', '~> 7.0.1'
  pod 'SwiftLint'
  
##### Remote Dependencies
  pod 'FPHISDKLicenseCheckerComponent', '~> 1.4.0'
  pod 'FPHISDKCoreComponent', '~> 1.4.0'
  pod 'FPHISDKLicensingComponent', '~> 1.4.0'
  pod 'FPHISDKMainComponent', '~> 1.4.0'
  pod 'FPHISDKTrackingComponent', '~> 1.4.0'
  pod 'FPHISDKSelphIDComponent', '~> 1.4.0'
  pod 'FPHISDKSelphiComponent', '~> 1.4.0'
  pod 'FPHISDKTokenizeComponent', '~> 1.4.0'
  
##### Use with local Sources
#  pod 'FPHISDKLicenseCheckerComponent', :path => "../../SDK-LicenseChecker-SPM/FPHISDKLicenseCheckerComponent-Test.podspec"
#  pod 'FPHISDKCoreComponent', :path => "../../SDK-Core-SPM/FPHISDKCoreComponent-Test.podspec"
#  pod 'FPHISDKLicensingComponent', :path => "../../SDK-Licensing-SPM/FPHISDKLicensingComponent-Test.podspec"
#  pod 'FPHISDKMainComponent',:path => "../../SDK-Sdk-SPM/FPHISDKMainComponent-Test.podspec"
#  pod 'FPHISDKSelphIDComponent',:path => "../../SDK-SelphidComponent/FPHISDKSelphIDComponent-Test.podspec"
#  pod 'FPHISDKTrackingComponent', :path => "../../SDK-Tracking_component-SPM/FPHISDKTrackingComponent-Test.podspec"
#  pod 'FPHISDKSelphiComponent',:path => "../../SDK-Selphi_component-SPM/FPHISDKSelphiComponent-Test.podspec"
#  pod 'FPHISDKTokenizeComponent', :path => "../../SDK-Tokenize-SPM/FPHISDKTokenizeComponent-Test.podspec"
#  pod 'FPHISDKBehaviorComponent',:path => "../../SDK-BehaviorComponent-SPM/FPHISDKBehaviorComponent-Test.podspec"

##### Use with local-compiled xcframeworks
#  pod 'FPHISDKLicenseCheckerComponent', :path => "../../SDK-LicenseChecker-SPM/FPHISDKLicenseCheckerComponent-template.podspec"
#  pod 'FPHISDKCoreComponent', :path => "../../SDK-Core-SPM/FPHISDKCoreComponent-template.podspec"
#  pod 'FPHISDKLicensingComponent', :path => "../../SDK-Licensing-SPM/FPHISDKLicensingComponent-template.podspec"
#  pod 'FPHISDKMainComponent',:path => "../../SDK-Sdk-SPM/FPHISDKMainComponent-template.podspec"
#  pod 'FPHISDKSelphIDComponent',:path => "../../SDK-SelphidComponent/FPHISDKSelphIDComponent-template.podspec"
#  pod 'FPHISDKTrackingComponent', :path => "../../SDK-Tracking_component-SPM/FPHISDKTrackingComponent-template.podspec"
#  pod 'FPHISDKSelphiComponent',:path => "../../SDK-Selphi_component-SPM/FPHISDKSelphiComponent-template.podspec"
#  pod 'FPHISDKTokenizeComponent', :path => "../../SDK-Tokenize-SPM/FPHISDKTokenizeComponent-template.podspec"
#  pod 'FPHISDKBehaviorComponent',:path => "../../SDK-BehaviorComponent-SPM/FPHISDKBehaviorComponent-template.podspec"

  target 'demosdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demosdkUITests' do
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'zipzap'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end

