# Uncomment the next line to define a global platform for your project
plugin 'cocoapods-art', :sources => [
  'cocoa-pro-fphi'
]

source 'https://cdn.cocoapods.org/'

target 'demosdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  ##### Use with remote Artifactory Pods
  pod 'FPHISDKMainComponent', '~> 2.10.0'
  pod 'FPHISDKTrackingComponent', '~> 2.10.0'
  pod 'FPHISDKNFCComponent', '~> 2.18.0'
  pod 'FPHISDKDisclaimerComponent', '~> 2.10.0'
  pod 'FPHISDKStatusComponent', '~> 2.10.0'
  pod 'FPHISDKTokenizeComponent', '~> 2.10.0'

  target 'demosdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demosdkUITests' do
    # Pods for testing
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'zipzap'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end

  # CocoaPods reorders build phases on pod install; keep compose copy after [CP] phases.
  installer.aggregate_targets
    .map(&:user_project)
    .uniq
    .each do |project|
      project.targets.each do |target|
        next unless target.name == 'demosdk'

        copy_phase = target.shell_script_build_phases.find { |phase| phase.name == 'Copy compose resources' }
        next unless copy_phase

        target.build_phases.delete(copy_phase)
        target.build_phases << copy_phase
      end
      project.save
    end
end
