# Uncomment the next line to define a global platform for your project
plugin 'cocoapods-art', :sources => [
  'cocoa-dev-fphi'
]

source 'https://cdn.cocoapods.org/'

target 'demosdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # TODO: Check why do we need this
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'

  ##### Use with remote Artifactory Pods
  pod 'FPHISDKLicenseCheckerComponent', '~> 1.4.0'
  pod 'FPHISDKCoreComponent', '~> 1.5.0'
  pod 'FPHISDKLicensingComponent', '~> 1.5.0'
  pod 'FPHISDKMainComponent', '~> 1.5.0'
  pod 'FPHISDKTrackingComponent', '~> 1.5.0'
  pod 'FPHISDKNFCComponent', '~> 2.7.0'
  pod 'FPHISDKStatusComponent', '~> 1.5.0'

  target 'demosdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demosdkUITests' do
    # Pods for testing
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'zipzap'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
