# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

 plugin 'cocoapods-art', :sources => [
   'cocoa-dev-fphi'
 ]

source 'https://cdn.cocoapods.org/'

target 'demosdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # TODO: Check why do we need this
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'

  ##### Use with remote Artifactory Pods
  pod 'FPHISDKTrackingComponent', '~> 1.4.0'
  pod 'FPHISDKNFCComponent', '~> 2.5.1'
  pod 'FPHISDKMainComponent', '~> 1.4.0'
  
  
  ##### Use with local Sources
  #  pod 'FPHISDKLicenseCheckerComponent', :path => "../../SDK-LicenseChecker-SPM/FPHISDKLicenseCheckerComponent-Test.podspec"
  #  pod 'FPHISDKCoreComponent', :path => "../../SDK-Core-SPM/FPHISDKCoreComponent-Test.podspec"
  #  pod 'FPHISDKLicensingComponent', :path => "../../SDK-Licensing-SPM/FPHISDKLicensingComponent-Test.podspec"
  #  pod 'FPHISDKMainComponent',:path => "../../SDK-Sdk-SPM/FPHISDKMainComponent-Test.podspec"
  #  pod 'FPHISDKTrackingComponent', :path => "../../SDK-Tracking_component-SPM/FPHISDKTrackingComponent-Test.podspec"
  #  pod 'FPHISDKNFCComponent',:path => "../../NFCDocumentReader/FPHISDKNFCComponent-Test.podspec"


  target 'demosdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demosdkUITests' do
    # Pods for testing
  end
end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end

end
